version: "3"
services:
  mailhog:
    image: jcalonso/mailhog:latest
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web interface
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
